import turtle               

"""wn = turtle.Screen()  

germany = turtle.Turtle()      
germany.color("black")
germany.pensize(50)
germany.forward(150)
germany.up()
germany.color("red")
germany.up()
germany.right(90)
germany.forward(50)
germany.right(90)
germany.down()
germany.forward(150)
germany.color("gold")
germany.up()
germany.left(90)
germany.forward(50)
germany.left(90)
germany.down()
germany.forward(150)

wn.exitonclick()

"""
"""
wn = turtle.Screen()        

denmark = turtle.Turtle()      
denmark.color("red")
denmark.pensize(200)
denmark.forward(150)
denmark.color("white")
denmark.pensize(40)
denmark.forward(80)
denmark.forward(-310)
denmark.up()
denmark.left(45)
denmark.forward(120)
denmark.down()
denmark.right(135)
denmark.forward(170)

wn.exitonclick()
"""
"""
#dutch

wn = turtle.Screen()

holland = turtle.Turtle()           # create tess and set some attributes
holland.color("red")
holland.pensize(50)
holland.up()
holland.forward(-250)
holland.down()
holland.forward(150)
holland.right(90)
holland.up()
holland.forward(100)
holland.right(90)
holland.color("blue")
holland.down()
holland.forward(150)

belgium = turtle.Turtle()
belgium.color("black")
belgium.right(90)
belgium.pensize(50)
belgium.forward(150)
belgium.up()
belgium.left(90)
belgium.forward(50)
belgium.left(90)
belgium.color("gold")
belgium.down()
belgium.forward(150)
belgium.up()
belgium.right(90)
belgium.forward(50)
belgium.right(90)
belgium.color("red")
belgium.down()
belgium.forward(150)

wn.exitonclick()
"""

#english

wn = turtle.Screen()
"""
#uk
uk = turtle.Turtle()
uk.color("blue")
uk.up()
uk.forward(-100)
uk.right(90)
uk.forward(-120)
uk.right(90)
uk.pensize(200)
uk.down()
uk.forward(150)
uk.pensize(40)
uk.up()
uk.right(90)
uk.forward(-70)
uk.right(90)
uk.forward(-30)
uk.left(33)
uk.color("white")
uk.down()
uk.forward(250)
uk.pensize(20)
uk.color("red")
uk.forward(-250)
uk.up()
uk.right(33)
uk.forward(200)
uk.left(327)
uk.color("white")
uk.pensize(40)
uk.forward(-250)
uk.down()
uk.forward(250)
uk.color("red")
uk.pensize(20)
uk.forward(-250)
uk.up()
uk.left(33)
uk.forward(110)
uk.right(90)
uk.pensize(40)
uk.color("white")
uk.down()
uk.forward(140)
uk.color("red")
uk.pensize(20)
uk.forward(-140)
uk.up()
uk.left(55)
uk.forward(130)
uk.left(35)
uk.pensize(40)
uk.color("white")
uk.down()
uk.forward(-220)
uk.color("red")
uk.pensize(20)
uk.forward(220)
#us
us = turtle.Turtle()
us.color("red")
us.pensize(10)
us.up()
us.forward(50)
for i in range(11): 
	us.down()
	us.forward(250)
	us.up()
	us.right(90)
	us.forward(15)
	us.right(90)
	us.forward(250)
	us.left(180)
	us.down()
us.up()
us.forward(25)
us.left(90)
us.forward(90)
us.right(90)
us.down()
us.color("blue")
us.pensize(60)
for i in range(4):
	us.forward(80)
	us.left(90)
	us.forward(50)
	us.left(90)
"""
#canada
canada = turtle.Turtle()
canada.color("red")
canada.up()
canada.forward(-250)
canada.right(90)
canada.forward(100)
canada.pensize(200)
canada.left(90)
canada.down()
canada.forward(150)
canada.up()
canada.forward(-75)
canada.left(90)
canada.forward(100)
canada.pensize(100)
canada.color("white")
canada.down()
canada.forward(-200)
canada.up()
canada.forward(100)
canada.color("red")
canada.shape("turtle")
canada.pensize(1)
canada.stamp()

wn.exitonclick()

"""
wn = turtle.Screen()        

sweden = turtle.Turtle()      
sweden.color("blue")
sweden.pensize(200)
sweden.forward(150)
sweden.color("gold")
sweden.pensize(40)
sweden.forward(80)
sweden.forward(-310)
sweden.up()
sweden.left(45)
sweden.forward(120)
sweden.down()
sweden.right(135)
sweden.forward(170)

wn.exitonclick()
"""
"""
wn = turtle.Screen()        

norway = turtle.Turtle()      
norway.color("red")
norway.pensize(200)
norway.forward(150)
norway.color("white")
norway.pensize(40)
norway.forward(80)
norway.forward(-310)
norway.up()
norway.left(45)
norway.forward(120)
norway.down()
norway.right(135)
norway.forward(170)
norway.color("blue")
norway.pensize(20)
norway.forward(-170)
norway.right(45)
norway.up()
norway.forward(120)
norway.down()
norway.left(135)
norway.forward(310)

wn.exitonclick()
"""
wn = turtle.Screen()        

iceland = turtle.Turtle()      
iceland.color("blue")
iceland.pensize(200)
iceland.forward(150)
iceland.color("white")
iceland.pensize(40)
iceland.forward(80)
iceland.forward(-310)
iceland.up()
iceland.left(45)
iceland.forward(120)
iceland.down()
iceland.right(135)
iceland.forward(170)
iceland.color("red")
iceland.pensize(20)
iceland.forward(-170)
iceland.right(45)
iceland.up()
iceland.forward(120)
iceland.down()
iceland.left(135)
iceland.forward(310)

wn.exitonclick()
