import turtle               

"""wn = turtle.Screen()  

germany = turtle.Turtle()      
germany.color("black")
germany.pensize(50)
germany.forward(150)
germany.up()
germany.color("red")
germany.up()
germany.right(90)
germany.forward(50)
germany.right(90)
germany.down()
germany.forward(150)
germany.color("gold")
germany.up()
germany.left(90)
germany.forward(50)
germany.left(90)
germany.down()
germany.forward(150)

wn.exitonclick()

"""
"""
wn = turtle.Screen()        

denmark = turtle.Turtle()      
denmark.color("red")
denmark.pensize(50)
denmark.forward(20)
denmark.up()
denmark.forward(60)
denmark.down()
denmark.forward(90)
denmark.up()
denmark.left(90)
denmark.forward(60)
denmark.down()
denmark.left(90)
denmark.forward(90)
denmark.up()
denmark.forward(60)
denmark.down()
denmark.forward(20)

wn.exitonclick()
"""
"""
#dutch

wn = turtle.Screen()

holland = turtle.Turtle()           # create tess and set some attributes
holland.color("red")
holland.pensize(50)
holland.up()
holland.forward(-250)
holland.down()
holland.forward(150)
holland.right(90)
holland.up()
holland.forward(100)
holland.right(90)
holland.color("blue")
holland.down()
holland.forward(150)

belgium = turtle.Turtle()
belgium.color("black")
belgium.right(90)
belgium.pensize(50)
belgium.forward(150)
belgium.up()
belgium.left(90)
belgium.forward(50)
belgium.left(90)
belgium.color("gold")
belgium.down()
belgium.forward(150)
belgium.up()
belgium.right(90)
belgium.forward(50)
belgium.right(90)
belgium.color("red")
belgium.down()
belgium.forward(150)

wn.exitonclick()
"""

#english

wn = turtle.Screen()

uk = turtle.Turtle()
uk.color("blue")
uk.up()
uk.forward(-100)
uk.right(90)
uk.forward(-120)
uk.right(90)
uk.pensize(200)
uk.down()
uk.forward(150)
uk.pensize(40)
uk.up()
uk.right(90)
uk.forward(-70)
uk.right(90)
uk.forward(-30)
uk.left(33)
uk.color("white")
uk.down()
uk.forward(250)
uk.pensize(20)
uk.color("red")
uk.forward(-250)
uk.up()
uk.right(33)
uk.forward(200)
uk.left(327)
uk.color("white")
uk.pensize(40)
uk.forward(-250)
uk.down()
uk.forward(250)
uk.color("red")
uk.pensize(20)
uk.forward(-250)
uk.up()
uk.left(33)
uk.forward(110)
uk.right(90)
uk.pensize(40)
uk.color("white")
uk.down()
uk.forward(140)
uk.color("red")
uk.pensize(20)
uk.forward(-140)
uk.up()
uk.left(55)
uk.forward(130)
uk.left(35)
uk.pensize(40)
uk.color("white")
uk.down()
uk.forward(-220)
uk.color("red")
uk.pensize(20)
uk.forward(220)





wn.exitonclick()